<?php
module_load_include('inc', 'flat_access_request_form', 'includes/db');

/**
 * Displaying flat request access form
 * and sending e-mail
 *
 * @return string
 */
function flat_access_request_form() {

    $entities = flat_access_request_form_entity();
    $response = theme('flat_access_request_form_not_found_template');

    if ($entities) {

        $entity = array_keys($entities['node']);
        $nid    = array_shift($entity);

        // hiding title
        $node = node_load($nid);
        $node->title = null;

        $view     = node_view($node);
        $response = render($view);
    }

    return $response;
}

/**
 * Theme
 *
 * @return array
 */
function flat_access_request_form_theme() {

    return [

        'flat_access_request_form_not_found_template' => [
            'template' => 'theme/flat-access-request-form-not-found',
        ],
    ];
}

/**
 * Permissions
 *
 * @return array
 */
function flat_access_request_form_permission() {

    return [
        'request access menu' => [
            'title' => t('FLAT Access Request Form'),
            'description' => t('Allows you to request access to certain objects, bundles or collections'),
        ],
    ];
}

/**
 * @return array
 */
function flat_access_request_form_menu() {

    $items = [];

    // request access form
    $items['islandora/object/%islandora_object/request_access'] = [

        'title'            => 'Request Access',
        'type'             => MENU_CALLBACK,
        'page callback'    => 'flat_access_request_form',
        'page arguments'   => [2],
        'access callback'  => 'flat_access_request_form_menu_access',
        'access arguments' => [2],
        'weight'           => 100,
    ];

    $items['admin/config/flat_deposit/flat_access_request_form'] = [

        'title'            => t('Configure FLAT Access Request Form'),
        'type'             => MENU_LOCAL_TASK,
        'page callback'    => 'drupal_get_form',
        'page arguments'   => ['flat_access_request_form_admin_form'],
        'access callback'  => 'flat_access_request_form_admin_menu_access',
        'file'             => 'includes/admin.inc',
    ];

    return $items;
}

function flat_access_request_form_admin_menu_access() {
    return true === user_access('request access menu');
}

/**
 * When to allow showing of tab
 *
 * @param AbstractObject $object
 *
 * @return boolean
 */
function flat_access_request_form_menu_access() {
    return true;
}

function flat_access_request_form_token_info() {

    return [

        'types' => [
            'flat' => [
                'name' => t('FLAT'),
                'description' => t('FLAT custom tokens'),
            ],
        ],
        'tokens' => [
            'flat' => [
                'url' => [
                    'name' => t('FLAT url'),
                    'description' => t('FLAT url generation of Fedora Object'),
                    'type' => 'fedora',
                ],
            ],
        ],
    ];
}

function flat_access_request_form_tokens($type, $tokens, array $data = [], array $options = []) {

    $replacements = [];

    if ($type === 'flat') {

        $object = $data['fedora'];
        foreach ($tokens as $name => $original) {

            if ($name === 'url') {
                $replacements[$original] = url('islandora/object/' . $object->id);
            }
        }

        return $replacements;
    }
}

/**
 * Hook into page preprocess to add
 * navigation links to title suffix
 *
 * @param array $variables
 *
 * @return void
 */
function flat_access_request_form_preprocess_page(&$variables) {

    if (drupal_get_http_header('status') !== '403 Forbidden') {

        // arg(3) === null means we are on the view page
        if (arg(0) === 'islandora' && arg(3) === null) {

            $object    = menu_get_object('islandora_object', 2);
            $no_access = flat_access_request_has_no_access($object);

            if (true === $no_access) {

                if (!isset($variables['title_suffix']['#markup'])) {
                    $variables['title_suffix']['#markup'] = '';
                }

                $request_access_path = url('islandora/object/' . arg(2) . '/request_access');

                $variables['title_suffix']['#markup'] = '<div style="margin-bottom: 10px;"><a href="' . $request_access_path . '">Request access</a></div>' . $variables['title_suffix']['#markup'];
            }
        }
    }
}
